package com.voicedrop.crypto

import com.google.crypto.tink.subtle.X25519
import com.voicedrop.network.FrameCodec
import java.security.MessageDigest
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * DR5 — initial root-key bootstrap.
 *
 * Two cases:
 *   - First pairing (R=0): `RK_0` mixes `idSharedSecret` AND a per-pairing
 *     X25519 ephemeral generated by the Bob role. Identity-key-only exfil
 *     cannot recompute `RK_0` without also extracting Bob's wrapped state.
 *   - Post-reset (R>0): `RK_0` mixes `idSharedSecret` AND the on-wire
 *     `resetNonce`. Identity-key exfil alone is sufficient — see
 *     plan/08-dr/00-overview.md §1 FS boundary.
 *
 * Role split is deterministic and stable across the lifetime of a contact:
 *     `myFp < peerFp ⇒ ALICE` (raw 32-byte SHA-256, unsigned compare).
 */
object Bootstrap {

    enum class Role { ALICE, BOB }

    /** HKDF info prefix per plan/08-dr/00-overview.md §3. */
    const val HKDF_PURPOSE = "voicedrop/rk-bootstrap/v2"

    const val ROOT_KEY_BYTES = 32
    const val RESET_NONCE_BYTES = 16
    const val X25519_BYTES = 32

    /**
     * Bob retains DHs (his bootstrap ephemeral); Alice retains DHr (Bob's
     * bootstrap pub). The opposite slots are null:
     *   ALICE: dhsPriv=null, dhsPub=null, dhrPub=bobEphPub
     *   BOB:   dhsPriv=bobEphPriv, dhsPub=bobEphPub, dhrPub=null
     *
     * Plain class (not data) — `ByteArray` reference-equality on a data class
     * would be misleading; callers compare per-field.
     */
    class InitialState(
        val role: Role,
        val rootKey: ByteArray,
        val dhsPriv: ByteArray?,
        val dhsPub: ByteArray?,
        val dhrPub: ByteArray?
    )

    /** Raw 32-byte SHA-256 of the X25519 identity public key (NOT the hex string). */
    fun fingerprintBytes(idPub: ByteArray): ByteArray {
        require(idPub.size == X25519_BYTES) { "idPub must be $X25519_BYTES bytes" }
        return MessageDigest.getInstance("SHA-256").digest(idPub)
    }

    fun decideRole(myIdPub: ByteArray, peerIdPub: ByteArray): Role {
        val myFp = fingerprintBytes(myIdPub)
        val peerFp = fingerprintBytes(peerIdPub)
        return if (compareUnsigned(myFp, peerFp) < 0) Role.ALICE else Role.BOB
    }

    /** First pairing. `ikm = idShared || bootstrapDH` (64 B); `info = prefix || 0x00 || be32(0)`. */
    fun deriveInitialRootKey(idShared: ByteArray, bootstrapDH: ByteArray): ByteArray {
        require(idShared.size == X25519_BYTES) { "idShared must be $X25519_BYTES bytes" }
        require(bootstrapDH.size == X25519_BYTES) { "bootstrapDH must be $X25519_BYTES bytes" }
        val ikm = ByteArray(idShared.size + bootstrapDH.size)
        idShared.copyInto(ikm, 0)
        bootstrapDH.copyInto(ikm, idShared.size)
        val info = buildInfo(R = 0, resetNonce = null)
        try {
            return hkdfSha256(salt = ByteArray(32), ikm = ikm, info = info, length = ROOT_KEY_BYTES)
        } finally {
            ikm.fill(0)
        }
    }

    /**
     * §3.2 — Post-reset RK_0. `ikm = idShared || prekeySS` (64 B);
     * `info = "voicedrop/rk-bootstrap/v2" || 0x00 || be32(R) || resetNonce`.
     *
     * `prekeySS` is the X25519 shared secret between the active prekey row
     * on each side at the moment the cycle starts (NOT the freshly-generated
     * staged prekey — see spec §3.4 "Where prekeySS comes from").
     */
    fun deriveResetRootKey(
        idShared: ByteArray,
        prekeySS: ByteArray,
        R: Int,
        resetNonce: ByteArray
    ): ByteArray {
        require(idShared.size == X25519_BYTES) { "idShared must be $X25519_BYTES bytes" }
        require(prekeySS.size == X25519_BYTES) { "prekeySS must be $X25519_BYTES bytes" }
        require(resetNonce.size == RESET_NONCE_BYTES) { "resetNonce must be $RESET_NONCE_BYTES bytes" }
        require(R > 0) { "deriveResetRootKey requires R > 0 (use deriveInitialRootKey for first pairing)" }
        val ikm = ByteArray(idShared.size + prekeySS.size)
        idShared.copyInto(ikm, 0)
        prekeySS.copyInto(ikm, idShared.size)
        val info = buildInfo(R = R, resetNonce = resetNonce)
        try {
            return hkdfSha256(salt = ByteArray(32), ikm = ikm, info = info, length = ROOT_KEY_BYTES)
        } finally {
            ikm.fill(0)
        }
    }

    /**
     * Run the full first-pairing bootstrap. Decides role, computes both DH outputs,
     * derives `RK_0`, and assigns DH state per role.
     *
     * Caller still owns wiping its own copies of the private byte arrays it passed
     * in — this function wipes only its internal intermediates.
     */
    fun computeInitialBootstrap(
        myIdPriv: ByteArray,
        myIdPub: ByteArray,
        peerIdPub: ByteArray,
        myBootstrapEphPriv: ByteArray,
        myBootstrapEphPub: ByteArray,
        peerBootstrapEphPub: ByteArray
    ): InitialState {
        require(myIdPriv.size == X25519_BYTES) { "myIdPriv size" }
        require(myIdPub.size == X25519_BYTES) { "myIdPub size" }
        require(peerIdPub.size == X25519_BYTES) { "peerIdPub size" }
        require(myBootstrapEphPriv.size == X25519_BYTES) { "myBootstrapEphPriv size" }
        require(myBootstrapEphPub.size == X25519_BYTES) { "myBootstrapEphPub size" }
        require(peerBootstrapEphPub.size == X25519_BYTES) { "peerBootstrapEphPub size" }
        // Same low-order/all-zero screen every other X25519 entry point applies
        // (Ratchet, ResetReceive): a tampered QR payload with a low-order peer
        // pub would collapse RK_0 to an attacker-known value.
        require(isValidX25519Public(peerIdPub)) { "peerIdPub rejected (all-zero/low-order)" }
        require(isValidX25519Public(peerBootstrapEphPub)) { "peerBootstrapEphPub rejected (all-zero/low-order)" }

        val role = decideRole(myIdPub, peerIdPub)
        val idShared = X25519.computeSharedSecret(myIdPriv, peerIdPub)

        // bootstrapDH = X25519(bobEphPriv, aliceIdPub).
        //   - BOB locally: bobEphPriv = myBootstrapEphPriv,  aliceIdPub = peerIdPub
        //   - ALICE locally: bobEphPriv is on peer; X25519 symmetry yields the same scalar
        //                    via X25519(myIdPriv, bobEphPub) where bobEphPub = peerBootstrapEphPub.
        val bootstrapDH = when (role) {
            Role.BOB -> X25519.computeSharedSecret(myBootstrapEphPriv, peerIdPub)
            Role.ALICE -> X25519.computeSharedSecret(myIdPriv, peerBootstrapEphPub)
        }

        val rk0 = try {
            deriveInitialRootKey(idShared, bootstrapDH)
        } finally {
            idShared.fill(0)
            bootstrapDH.fill(0)
        }

        return when (role) {
            Role.BOB -> InitialState(
                role = Role.BOB,
                rootKey = rk0,
                dhsPriv = myBootstrapEphPriv.copyOf(),
                dhsPub = myBootstrapEphPub.copyOf(),
                dhrPub = null
            )
            Role.ALICE -> InitialState(
                role = Role.ALICE,
                rootKey = rk0,
                dhsPriv = null,
                dhsPub = null,
                dhrPub = peerBootstrapEphPub.copyOf()
            )
        }
    }

    private fun buildInfo(R: Int, resetNonce: ByteArray?): ByteArray {
        val prefix = HKDF_PURPOSE.toByteArray(Charsets.UTF_8)
        val tail = 4 + (resetNonce?.size ?: 0)
        val out = ByteArray(prefix.size + 1 + tail)
        var p = 0
        prefix.copyInto(out, p); p += prefix.size
        out[p++] = 0x00
        out[p++] = (R ushr 24).toByte()
        out[p++] = (R ushr 16).toByte()
        out[p++] = (R ushr 8).toByte()
        out[p++] = R.toByte()
        resetNonce?.copyInto(out, p)
        return out
    }

    private fun isValidX25519Public(pub: ByteArray): Boolean =
        !FrameCodec.isAllZero(pub) && !FrameCodec.isLowOrderX25519(pub)

    private fun compareUnsigned(a: ByteArray, b: ByteArray): Int {
        require(a.size == b.size) { "fingerprint size mismatch" }
        for (i in a.indices) {
            val av = a[i].toInt() and 0xff
            val bv = b[i].toInt() and 0xff
            if (av != bv) return av - bv
        }
        return 0
    }

    private fun hkdfSha256(salt: ByteArray, ikm: ByteArray, info: ByteArray, length: Int): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        val actualSalt = if (salt.isEmpty()) ByteArray(32) else salt
        mac.init(SecretKeySpec(actualSalt, "HmacSHA256"))
        val prk = mac.doFinal(ikm)
        mac.init(SecretKeySpec(prk, "HmacSHA256"))
        val out = ByteArray(length)
        var t = ByteArray(0)
        var pos = 0
        var counter = 1
        while (pos < length) {
            mac.update(t); mac.update(info); mac.update(counter.toByte())
            t = mac.doFinal()
            val len = minOf(t.size, length - pos)
            t.copyInto(out, pos, 0, len)
            pos += len; counter++
        }
        return out
    }
}
